-- 1. Create site_settings table if it doesn't exist
create table if not exists public.site_settings (
    id bigint generated by default as identity primary key,
    whatsapp_number text default '905000000000',
    iban_list text, -- Deprecated
    site_name text default 'HAKTAN Kuruyemiş Şarküteri Sarayı',
    contact_email text default 'iletisim@haktan.com',
    address text default 'Haktan Sarayı, İstanbul',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create bank_accounts table if it doesn't exist
create table if not exists public.bank_accounts (
    id bigint generated by default as identity primary key,
    bank_name text not null,
    account_holder text not null,
    iban text not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.site_settings enable row level security;
alter table public.bank_accounts enable row level security;

-- 4. Policies (Drop if exists then create to avoid errors)
do $$ 
begin
    -- site_settings policies
    if not exists (select 1 from pg_policies where policyname = 'Enable read access for all' and tablename = 'site_settings') then
        create policy "Enable read access for all" on public.site_settings for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Enable all access for all' and tablename = 'site_settings') then
        create policy "Enable all access for all" on public.site_settings for all using (true) with check (true);
    end if;

    -- bank_accounts policies
    if not exists (select 1 from pg_policies where policyname = 'Enable read access for all' and tablename = 'bank_accounts') then
        create policy "Enable read access for all" on public.bank_accounts for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Enable all access for all' and tablename = 'bank_accounts') then
        create policy "Enable all access for all" on public.bank_accounts for all using (true) with check (true);
    end if;
end $$;

-- 5. Insert default data safely
insert into public.site_settings (id, whatsapp_number, site_name, contact_email, address)
values (1, '905000000000', 'HAKTAN Kuruyemiş Şarküteri Sarayı', 'iletisim@haktan.com', 'Haktan Sarayı, İstanbul')
on conflict (id) do nothing;

insert into public.bank_accounts (bank_name, account_holder, iban)
select 'Ziraat Bankası', 'Haktan Kuruyemiş Ltd. Şti.', 'TR12 0001 0002 0003 0004 0005 06'
where not exists (select 1 from public.bank_accounts where bank_name = 'Ziraat Bankası');
